# Generated by Django 4.2.2 on 2024-04-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_alter_employerparentagedetails_application_certificate_establishment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationforcertificateofestablishment',
            name='registration_status',
        ),
    ]
