# Generated by Django 4.2.2 on 2024-04-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_remove_applicationforcertificateofestablishment_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationforcertificateofestablishment',
            name='registration_status',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
