# Generated by Django 4.2.2 on 2024-04-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_applicationforcertificateofestablishment_registration_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerdetails',
            name='application_certificate_establishment',
        ),
        migrations.RemoveField(
            model_name='employerfamilymemberdetails',
            name='application_certificate_establishment',
        ),
        migrations.RemoveField(
            model_name='employerparentagedetails',
            name='application_certificate_establishment',
        ),
        migrations.RemoveField(
            model_name='managementlevelemployeedetails',
            name='application_certificate_establishment',
        ),
        migrations.DeleteModel(
            name='ApplicationForCertificateOfEstablishment',
        ),
        migrations.DeleteModel(
            name='EmployerDetails',
        ),
        migrations.DeleteModel(
            name='EmployerFamilyMemberDetails',
        ),
        migrations.DeleteModel(
            name='EmployerParentageDetails',
        ),
        migrations.DeleteModel(
            name='ManagementLevelEmployeeDetails',
        ),
    ]
