# Generated by Django 4.2.2 on 2024-04-06 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('operation', '0005_remove_employerdetails_application_certificate_establishment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForCertificateOfEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_status', models.CharField(max_length=128)),
                ('full_name_applicant', models.CharField(max_length=256)),
                ('email_applicant', models.CharField(max_length=256)),
                ('photograph_applicant', models.FileField(blank=True, null=True, upload_to='applicant/photograph/')),
                ('establishment_name', models.CharField(max_length=256)),
                ('establishment_address', models.CharField(max_length=256)),
                ('establishment_pincode', models.CharField(max_length=6)),
                ('situation_of_other_premises', models.CharField(max_length=1024)),
                ('nature_business', models.CharField(max_length=1024)),
                ('total_emplyee_male_18', models.IntegerField(default=0)),
                ('total_emplyee_female_18', models.IntegerField(default=0)),
                ('total_emplyee_other_18', models.IntegerField(default=0)),
                ('total_emplyee_male_14', models.IntegerField(default=0)),
                ('total_emplyee_female_14', models.IntegerField(default=0)),
                ('total_emplyee_other_14', models.IntegerField(default=0)),
                ('weekly_holidays_name', models.CharField(max_length=256)),
                ('is_agreed_terms_and_condition', models.BooleanField(default=False)),
                ('applied_office_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_for_est', to='master.officedetails')),
                ('establishment_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_for_est', to='master.establishmentcategory')),
            ],
        ),
    ]
