# Generated by Django 4.2.2 on 2024-04-06 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('operation', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationforcertificateofestablishment',
            name='office_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.district'),
        ),
    ]
