# Generated by Django 4.2.2 on 2024-04-06 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_alter_applicationforcertificateofestablishment_office_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementLevelEmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.DecimalField(decimal_places=2, max_digits=5)),
                ('relationship', models.CharField(max_length=128)),
                ('application_certificate_establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_level_employee', to='operation.applicationforcertificateofestablishment')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerParentageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentage_name', models.CharField(max_length=256)),
                ('designation', models.CharField(max_length=128)),
                ('permanent_address', models.CharField(max_length=128)),
                ('nature_interest', models.CharField(max_length=128)),
                ('application_certificate_establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_parentel_details', to='operation.applicationforcertificateofestablishment')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerFamilyMemberDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.DecimalField(decimal_places=2, max_digits=5)),
                ('relationship', models.CharField(max_length=128)),
                ('application_certificate_establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_family_member', to='operation.applicationforcertificateofestablishment')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=128)),
                ('permanent_address', models.CharField(max_length=512)),
                ('application_certificate_establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_details', to='operation.applicationforcertificateofestablishment')),
            ],
        ),
    ]
