# Generated by Django 4.2.2 on 2024-04-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_managementlevelemployeedetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerfamilymemberdetails',
            name='gender',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managementlevelemployeedetails',
            name='gender',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
