# Generated by Django 4.2.2 on 2024-04-12 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0010_employerfamilymemberdetails_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationforcertificateofestablishment',
            name='application_status',
            field=models.CharField(default='received', max_length=128),
        ),
        migrations.AddField(
            model_name='applicationforcertificateofestablishment',
            name='applied_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appl_for_certificate_est', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationforcertificateofestablishment',
            name='approved_at',
            field=models.DateTimeField(default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationforcertificateofestablishment',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appr_for_certificate_est', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationforcertificateofestablishment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationforcertificateofestablishment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ApplicationProgressHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField()),
                ('application_status', models.CharField(default='received', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_progress_history', to='operation.applicationforcertificateofestablishment')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_progress_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
