# Generated by Django 4.2.2 on 2024-04-20 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_applicationforcertificateofestablishment_application_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationprogresshistory',
            old_name='application',
            new_name='application_certificate_establishment',
        ),
    ]
