# Generated by Django 4.2.2 on 2024-04-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_rename_application_applicationprogresshistory_application_certificate_establishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationforcertificateofestablishment',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
