<<<<<<< HEAD
# Generated by Django 4.2.2 on 2024-04-25 05:22
=======
# Generated by Django 4.2.2 on 2024-04-25 05:07
>>>>>>> 7c06e6c5551d453ed2a0c056a8991f3fb930d1f1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_rename_application_applicationprogresshistory_application_certificate_establishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationforcertificateofestablishment',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
