# Generated by Django 4.2.2 on 2024-04-26 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0013_alter_applicationforcertificateofestablishment_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationforcertificateofestablishment',
            name='pull_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationforcertificateofestablishment',
            name='pulled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appr_for_certificate_est_pulled_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationforcertificateofestablishment',
            name='applied_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appl_for_certificate_est_applied_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationforcertificateofestablishment',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appr_for_certificate_est_approved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
