# Generated by Django 4.2.2 on 2024-05-29 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0014_applicationforcertificateofestablishment_pull_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationprogresshistory',
            old_name='application_certificate_establishment',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='employerdetails',
            old_name='application_certificate_establishment',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='employerfamilymemberdetails',
            old_name='application_certificate_establishment',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='employerparentagedetails',
            old_name='application_certificate_establishment',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='managementlevelemployeedetails',
            old_name='application_certificate_establishment',
            new_name='application',
        ),
    ]
