# Generated by Django 4.2.2 on 2024-05-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0015_rename_application_certificate_establishment_applicationprogresshistory_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationprogresshistory',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
