# Generated by Django 4.2.2 on 2024-06-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0017_applicationforcertificateofestablishment_calculated_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=50)),
                ('sequence', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='applicationforcertificateofestablishment',
            name='application_no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
