# Generated by Django 4.2.2 on 2024-09-29 06:06

import common.custom_model_fields_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0018_applicationnumbersequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationforcertificateofestablishment',
            name='trade_licence',
            field=models.FileField(null=True, upload_to='applicant/trade_licence/', validators=[common.custom_model_fields_validator.FileExtensionValidator(['.jpg', '.jpeg', '.png', '.pdf']), common.custom_model_fields_validator.FileSizeValidator(10485760), common.custom_model_fields_validator.FileMimeTypeValidator(['image/jpeg', 'image/png', 'application/pdf'])]),
        ),
        migrations.AlterField(
            model_name='applicationforcertificateofestablishment',
            name='photograph_applicant',
            field=models.FileField(null=True, upload_to='applicant/photograph/', validators=[common.custom_model_fields_validator.FileExtensionValidator(['.jpg', '.jpeg', '.png', '.pdf']), common.custom_model_fields_validator.FileSizeValidator(10485760), common.custom_model_fields_validator.FileMimeTypeValidator(['image/jpeg', 'image/png', 'application/pdf'])]),
        ),
    ]
