# Generated by Django 4.2.2 on 2024-11-24 05:08

import common.custom_model_fields_validator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_officedetails_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0020_alter_applicationprogresshistory_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldCertificateOfEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, null=True)),
                ('date_of_registrations', models.DateField(null=True)),
                ('establishment_name', models.CharField(max_length=256, null=True)),
                ('establishment_address', models.CharField(max_length=256, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('establishment_pincode', models.CharField(max_length=6, null=True)),
                ('name_employer', models.CharField(max_length=256, null=True)),
                ('name_manager', models.CharField(max_length=256, null=True)),
                ('nature_business', models.CharField(max_length=1024, null=True)),
                ('establishment_category', models.CharField(max_length=128, null=True)),
                ('total_emplyee_male', models.IntegerField(default=0)),
                ('total_emplyee_female', models.IntegerField(default=0)),
                ('registration_certificate', models.FileField(null=True, upload_to='applicant/registration_certificate/', validators=[common.custom_model_fields_validator.FileExtensionValidator(['.jpg', '.jpeg', '.png', '.pdf']), common.custom_model_fields_validator.FileSizeValidator(10485760), common.custom_model_fields_validator.FileMimeTypeValidator(['image/jpeg', 'image/png', 'application/pdf'])])),
                ('application_status', models.CharField(default='received', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(null=True)),
                ('remarks', models.CharField(max_length=1028, null=True)),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_certificate_of_establishment_applied_by', to=settings.AUTH_USER_MODEL)),
                ('applied_office_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_certificate_of_establishment', to='master.officedetails')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_certificate_of_establishment_approved_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_certificate_of_establishment_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
