# Generated by Django 4.2.2 on 2024-11-24 13:42

import common.custom_model_fields_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0021_oldcertificateofestablishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldcertificateofestablishment',
            name='date_of_registrations',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='oldcertificateofestablishment',
            name='registration_certificate',
            field=models.FileField(null=True, upload_to='applicant/old/registration_certificate/', validators=[common.custom_model_fields_validator.FileExtensionValidator(['.jpg', '.jpeg', '.png', '.pdf']), common.custom_model_fields_validator.FileSizeValidator(10485760), common.custom_model_fields_validator.FileMimeTypeValidator(['image/jpeg', 'image/png', 'application/pdf'])]),
        ),
    ]
