# Generated by Django 4.2.2 on 2024-12-24 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0022_alter_oldcertificateofestablishment_date_of_registrations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_certification', models.IntegerField()),
                ('application_no', models.CharField(blank=True, default='', max_length=20)),
                ('payment_received_for', models.CharField(max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_received_through', models.CharField(max_length=20)),
                ('bank_receipt_no', models.CharField(blank=True, default='', max_length=20)),
                ('date_of_payment', models.DateField()),
                ('reference_id', models.CharField(max_length=20)),
                ('transaction_status', models.CharField(max_length=20)),
                ('transaction_status_message', models.CharField(max_length=128)),
                ('encdata', models.CharField(max_length=1028)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
