# Generated by Django 4.2.2 on 2025-02-03 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0023_paymentdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
    ]
