# Generated by Django 4.2.2 on 2024-04-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bar_certificate',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bar_registration_number',
        ),
    ]
