# Generated by Django 4.2.2 on 2024-04-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userprofile_bar_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='contact',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
