# Generated by Django 4.2.2 on 2024-04-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userotp_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='opt_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
