# Generated by Django 4.2.2 on 2024-04-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userotp_opt_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
