# Generated by Django 4.2.2 on 2025-01-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/2025'),
        ),
    ]
