# Generated by Django 4.2.2 on 2024-04-06 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(default=None, max_length=128, unique=True)),
                ('short_name', models.CharField(blank=True, default=None, max_length=5, null=True, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=None, max_length=512, unique=True)),
                ('short_name', models.CharField(blank=True, default=None, max_length=5, null=True, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=128, unique=True)),
                ('short_name', models.CharField(blank=True, default=None, max_length=5, null=True, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=None, max_length=512, null=True)),
                ('pin', models.CharField(default=None, max_length=512, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('district', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_details', to='master.district')),
                ('office_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_details', to='master.officetype')),
            ],
        ),
    ]
