# Generated by Django 4.2.2 on 2024-10-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='ref_no_prefix',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, unique=True),
        ),
    ]
