# Generated by Django 4.2.2 on 2024-10-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_district_ref_no_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='officedetails',
            name='office',
            field=models.CharField(default=None, max_length=512, null=True, unique=True),
        ),
    ]
