# Generated by Django 4.2.2 on 2024-12-24 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchent_id', models.CharField(max_length=50)),
                ('unique_transaction_id', models.CharField(max_length=50)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('na_field_1', models.CharField(default='NA', max_length=128)),
                ('na_field_2', models.CharField(default='NA', max_length=128)),
                ('na_field_3', models.CharField(default='NA', max_length=128)),
                ('currency_type', models.CharField(default='INR', max_length=3)),
                ('na_field_4', models.CharField(default='NA', max_length=128)),
                ('type_field_1', models.CharField(default='NA', max_length=128)),
                ('security_id', models.CharField(default='NA', max_length=128)),
                ('na_field_5', models.CharField(default='NA', max_length=128)),
                ('na_field_6', models.CharField(default='NA', max_length=128)),
                ('type_field_2', models.CharField(default='NA', max_length=128)),
                ('additional_field_1', models.CharField(default='NA', max_length=128)),
                ('additional_field_2', models.CharField(default='NA', max_length=128)),
                ('additional_field_3', models.CharField(default='NA', max_length=128)),
                ('additional_field_4', models.CharField(default='NA', max_length=128)),
                ('additional_field_5', models.CharField(default='NA', max_length=128)),
                ('additional_field_6', models.CharField(default='NA', max_length=128)),
                ('additional_field_7', models.CharField(default='NA', max_length=128)),
                ('return_url', models.CharField(default='NA', max_length=256)),
                ('checksum', models.CharField(default='NA', max_length=256)),
                ('res_merchant_id', models.CharField(default='NA', max_length=50, null=True)),
                ('res_unique_txn_id', models.CharField(default='NA', max_length=50, null=True)),
                ('res_txn_reference_no', models.CharField(default='NA', max_length=50, null=True)),
                ('res_bank_reference_no', models.CharField(default='NA', max_length=50, null=True)),
                ('res_txn_amount', models.CharField(default='NA', max_length=50, null=True)),
                ('res_bank_id', models.CharField(default='NA', max_length=50, null=True)),
                ('res_bin', models.CharField(default='NA', max_length=50, null=True)),
                ('res_txn_type', models.CharField(default='NA', max_length=2, null=True)),
                ('res_currency_name', models.CharField(default='NA', max_length=3, null=True)),
                ('res_item_code', models.CharField(default='NA', max_length=50, null=True)),
                ('res_sucurity_type', models.CharField(default='NA', max_length=50, null=True)),
                ('res_security_id', models.CharField(default='NA', max_length=50, null=True)),
                ('res_security_password', models.CharField(default='NA', max_length=50, null=True)),
                ('res_txn_date', models.DateTimeField(null=True)),
                ('res_auth_status', models.CharField(max_length=50, null=True)),
                ('res_settlement_type', models.CharField(max_length=50, null=True)),
                ('res_additional_info_1', models.CharField(default='NA', max_length=50, null=True)),
                ('res_additional_info_2', models.CharField(default='NA', max_length=50, null=True)),
                ('res_additional_info_3', models.CharField(default='NA', max_length=50, null=True)),
                ('res_additional_info_4', models.CharField(default='NA', max_length=50, null=True)),
                ('res_additional_info_5', models.CharField(default='NA', max_length=50, null=True)),
                ('res_additional_info_6', models.CharField(default='NA', max_length=50, null=True)),
                ('res_additional_info_7', models.CharField(default='NA', max_length=50, null=True)),
                ('res_error_status', models.CharField(default='NA', max_length=50, null=True)),
                ('res_error_descriptio', models.CharField(default='NA', max_length=128, null=True)),
                ('res_checksum', models.CharField(default='NA', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
