# Generated by Django 4.2.2 on 2024-12-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='na_field_7',
            field=models.CharField(default='NA', max_length=128),
        ),
    ]
