# Generated by Django 4.2.2 on 2025-01-24 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_paymentdetails_na_field_7'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDeskTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercid', models.CharField(help_text='Merchant ID', max_length=50)),
                ('orderid', models.CharField(help_text='Order ID', max_length=50, unique=True)),
                ('bdorderid', models.CharField(blank=True, help_text='BillDesk Order ID', max_length=50, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Order Amount', max_digits=10)),
                ('order_date', models.DateTimeField(help_text='Order Date and Time')),
                ('currency', models.CharField(help_text='Currency Code', max_length=10)),
                ('ru', models.URLField(help_text='Return URL', max_length=255)),
                ('itemcode', models.CharField(help_text='Item Code', max_length=50)),
                ('status', models.CharField(blank=True, help_text='Order Status', max_length=20, null=True)),
                ('createdon', models.DateTimeField(blank=True, help_text='Order Creation Date', null=True)),
                ('next_step', models.CharField(blank=True, help_text='Next Step (e.g., redirect)', max_length=50, null=True)),
                ('additional_info1', models.CharField(blank=True, help_text='Additional Info 1', max_length=255, null=True)),
                ('additional_info2', models.CharField(blank=True, help_text='Additional Info 2', max_length=255, null=True)),
                ('additional_info7', models.CharField(blank=True, help_text='Additional Info 7 (e.g., whatsapp)', max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, help_text='Invoice Number', max_length=50, null=True)),
                ('invoice_display_number', models.CharField(blank=True, help_text='Invoice Display Number', max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, help_text='Customer Name', max_length=100, null=True)),
                ('invoice_date', models.DateTimeField(blank=True, help_text='Invoice Date', null=True)),
                ('gst_cgst', models.DecimalField(blank=True, decimal_places=2, help_text='CGST Amount', max_digits=10, null=True)),
                ('gst_sgst', models.DecimalField(blank=True, decimal_places=2, help_text='SGST Amount', max_digits=10, null=True)),
                ('gst_igst', models.DecimalField(blank=True, decimal_places=2, help_text='IGST Amount', max_digits=10, null=True)),
                ('gst_total', models.DecimalField(blank=True, decimal_places=2, help_text='Total GST Amount', max_digits=10, null=True)),
                ('gst_cess', models.DecimalField(blank=True, decimal_places=2, help_text='GST CESS Amount', max_digits=10, null=True)),
                ('gst_incentive', models.DecimalField(blank=True, decimal_places=2, help_text='GST Incentive', max_digits=10, null=True)),
                ('gst_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='GST Percentage', max_digits=5, null=True)),
                ('gstin', models.CharField(blank=True, help_text='GSTIN Number', max_length=50, null=True)),
                ('device_ip', models.GenericIPAddressField(blank=True, help_text='Customer IP Address', null=True)),
                ('device_user_agent', models.TextField(blank=True, help_text='User Agent', null=True)),
                ('transaction_date', models.DateTimeField(blank=True, help_text='Transaction Date and Time', null=True)),
                ('surcharge', models.DecimalField(blank=True, decimal_places=2, help_text='Surcharge Amount', max_digits=10, null=True)),
                ('payment_method_type', models.CharField(blank=True, help_text='Payment Method Type', max_length=50, null=True)),
                ('transactionid', models.CharField(blank=True, help_text='Transaction ID', max_length=100, null=True, unique=True)),
                ('txn_process_type', models.CharField(blank=True, help_text='Transaction Process Type', max_length=50, null=True)),
                ('bankid', models.CharField(blank=True, help_text='Bank ID', max_length=50, null=True)),
                ('auth_status', models.CharField(blank=True, help_text='Authorization Status', max_length=10, null=True)),
                ('charge_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total Charged Amount', max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount Amount', max_digits=10, null=True)),
                ('authorization_token', models.TextField(blank=True, help_text='Authorization Token in Headers', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
    ]
