# Generated by Django 4.2.2 on 2025-02-03 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0003_billdesktransaction_delete_paymentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=50)),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('txn_reference_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_reference_no', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_name', models.CharField(default='INR', max_length=10)),
                ('txn_type', models.CharField(blank=True, max_length=50, null=True)),
                ('txn_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='INITIATED', max_length=20)),
                ('security_id', models.CharField(blank=True, max_length=50, null=True)),
                ('security_password', models.CharField(blank=True, max_length=50, null=True)),
                ('security_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ibank_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_merchant_id', models.CharField(blank=True, max_length=50, null=True)),
                ('item_code', models.CharField(blank=True, max_length=50, null=True)),
                ('auth_status', models.CharField(blank=True, max_length=50, null=True)),
                ('settlement_type', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_info1', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info2', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info3', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info4', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info5', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info6', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info7', models.CharField(blank=True, max_length=255, null=True)),
                ('na1', models.CharField(default='NA', max_length=50)),
                ('na2', models.CharField(default='NA', max_length=50)),
                ('na3', models.CharField(default='NA', max_length=50)),
                ('na4', models.CharField(default='NA', max_length=50)),
                ('na5', models.CharField(default='NA', max_length=50)),
                ('na6', models.CharField(default='NA', max_length=50)),
                ('na7', models.CharField(default='NA', max_length=50)),
                ('error_status', models.CharField(blank=True, max_length=50, null=True)),
                ('error_description', models.TextField(blank=True, null=True)),
                ('checksum', models.CharField(max_length=100)),
                ('request_payload', models.TextField(blank=True, null=True)),
                ('response_payload', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BillDeskTransaction',
        ),
    ]
