# Generated by Django 4.2.2 on 2025-02-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_paymenttransaction_delete_billdesktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='type_field1',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='type_field2',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
