# Generated by Django 4.2.2 on 2025-02-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_paymenttransaction_type_field1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='application',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='application_generation',
            field=models.CharField(choices=[('NEW', 'New'), ('OLD', 'Old')], default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='application_no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='type_field1',
            field=models.CharField(default='R', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='type_field2',
            field=models.CharField(default='F', max_length=50),
        ),
    ]
